Rpi
asynx-dev/www pull request #136
Opened 2021-03-28 14:50 UTC by alperyazar

**Turkish: RPi SD kart taşıma ve genişletme ile ilgili yazı eklendi.**

---
(Please remove or uncheck items that you don't agree)

As original author of this pull request (PR):

* [x] I read the current [CONTRIBUTING](https://github.com/asynx-dev/www/blob/master/CONTRIBUTING.md) document,
especially `Policies and Rules` and `Guides` sections and I am okay with
them.
* [x] I think that no material (text, audio, visual, etc.) pushed with this PR
violates any copyright, license rule. Either I created materials or they can
be published with repo [LICENSE](https://github.com/asynx-dev/www/blob/master/LICENSE). If a material is owned by
somebody else I added it with obeying its license rule like giving link to
original creator, etc.

---

Ping @asynx-dev/www-maintainers

2021-03-30 04:06 UTC, aniltirli approved these changes
Birkaç ekran görüntüsü güzel olabilirmiş. :) Eline sağlık abi.

2021-03-30 05:18 UTC, alperyazar commented
> Birkaç ekran görüntüsü güzel olabilirmiş. :) Eline sağlık abi.

Kısmet :) Çok görsel bir şey yoktu ama daha iyi olurdu tabii. Teşekkürler baktığın için.

2021-04-01 06:29 UTC, yunusesergun requested changes
Ellerine sağlık abi.

2021-04-01 06:29 UTC, yunusesergun commented on src/_posts/2021-03-28-rpi-sd-kart-buyutme.md
> +açılan ekrandan
Şurada ufak bir yazım hatası var sanırım.

2021-04-01 09:37 UTC, alperyazar commented on src/_posts/2021-03-28-rpi-sd-kart-buyutme.md
> +açılan ekrandan
Ben hala göremedim 😅

2021-04-01 16:10 UTC, alperyazar commented on src/_posts/2021-03-28-rpi-sd-kart-buyutme.md
> +açılan ekrandan
Sonradan anladım düzelttim 👍

2021-04-01 20:26 UTC, yunusesergun approved these changes
Tekrardan eline sağlık abi.

2021-04-02 10:22 UTC, merged