MIG Calibration Signal Does Not Go High Problemi Konusunda Cozum Onerileri Listelendi
asynx-dev/www pull request #16
Opened 2020-10-21 11:03 UTC by yunusesergun

2020-10-21 13:16 UTC, alperyazar commented on docs/index.md
> +![MIG Calibration Error](MIG_calibration_error/MIG.md)
Bu resim koymak için, link için düzeltilmeli.

2020-10-21 13:23 UTC, yunusesergun commented
Direk buradan editledim, umarım bir sıkıntı oluşturmamıştır.

2020-10-21 13:35 UTC, alperyazar requested changes
ek olarak `favicon.ico` bu commitle değişmemeli

2020-10-21 13:35 UTC, alperyazar commented on docs/index.md
> +
Ekstra boş satırı silelim

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +
Dosyalaırn sonunda sadece tek bir boş satır olmalı.

2020-10-21 13:35 UTC, alperyazar commented on docs/index.md
> +![MIG Calibration Error](MIG_calibration_error/MIG.md)
Bu resim koymak için, link için düzeltilmeli.

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +**4)** **Check Data Mask**  --> In the Options for Controller page of MIG interface, there is an option called "**Data Mask**". If you do not utilize AXI4 user interface feature, you have a chance to
typo: "otomatically"

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +After configuring your 7-Series MIG, you will notice that there is an important signal called "**init_calib_complete**". Calibration is the first stage of MIG if you run the code. MIG arranges phasor
Sinyal isimlerini **bold** veya *italik* yerine `şu şekilde` ` `` ` arasına alarak yapmak daha iyi olacaktır.

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +**4)** **Check Data Mask**  --> In the Options for Controller page of MIG interface, there is an option called "**Data Mask**". If you do not utilize AXI4 user interface feature, you have a chance to
"this Xilinx forum **thread**"

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +After configuring your 7-Series MIG, you will notice that there is an important signal called "**init_calib_complete**". Calibration is the first stage of MIG if you run the code. MIG arranges phasor
10. satırın sonunda whitespace var, onu kaldıralım.

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +Page Name    | Setting Name | Instruction
Tablo karakterlerinin etrafındaki whitespace'leri kaldıralım. Pin Selection for Controller'ın ikinci sütunundaki ---- lerin uzun olmasının bir anlamı var mı?

2020-10-21 13:35 UTC, alperyazar commented on docs/MIG_calibration_error/MIG.md
> +**2)** **Check All Resets** --> There are 3 resets in MIG, which are *sys_rst*, *aresetn* and *ui_clk_sync_rst*. If you do not connect *sys_rst pin* to a port from your FPGA and you want to give it a
--> yerine → kullanabiliriz. Ref: https://www.w3schools.com/charsets/ref_utf_arrows.asp

2020-10-21 13:37 UTC, alperyazar commented
@aniltirli sen de içerik vs olarak bakabilir misin?

2020-10-21 13:39 UTC, alperyazar requested changes
Özellikle favicon commit'ten çıkarlımalı

2020-10-21 13:48 UTC, yunusesergun commented
Tamamdır abi teşekkürler,  boşluk bir anımda düzelteceğim.

2020-10-26 17:37 UTC, alperyazar approved these changes
Build checklerden geçince yayına alırız. Tablonun etrafında linter 80 satır kuralını kapatabilirsin.

2020-10-26 17:38 UTC, alperyazar commented
@aniltirli Ben görüşlerimi ilettim var mı senin?

2020-10-28 06:38 UTC, aniltirli commented
> @aniltirli Ben görüşlerimi ilettim var mı senin?

benim gözüme çarpan birşey olmadı.

2020-10-28 08:57 UTC, alperyazar commented
> 
> 
> > @aniltirli Ben görüşlerimi ilettim var mı senin?
> 
> benim gözüme çarpan birşey olmadı.

Bu sayfada bir yerlerde reviewer olarak approve diyebileceğin bir düğme olması lazım. Oradan approve diyebilir misin? Şu an sende bekliyor gözüküyor da.

2020-10-28 17:27 UTC, aniltirli approved these changes

2020-11-09 13:12 UTC, merged

2021-03-13 16:57 UTC, alperyazar commented
@all-contributors add @yunusesergun blog, add @aniltirli and @alperyazar for review

2021-03-13 16:58 UTC, alperyazar commented
@all-contributors add @yunusesergun blog
@all-contributors add @aniltirli and @alperyazar for review

2021-03-13 16:58 UTC, alperyazar commented
@all-contributors add @aniltirli and @alperyazar for review

2021-03-13 17:00 UTC, alperyazar commented
@all-contributors add @alperyazar review
@all-contributors add @yunusesergun blog

2021-03-13 17:00 UTC, alperyazar commented
@all-contributors add @alperyazar review

2021-03-13 17:00 UTC, alperyazar commented
@all-contributors add @yunusesergun blog

2021-03-13 17:11 UTC, alperyazar commented
@all-contributors add @yunusesergun blog

2021-03-13 17:13 UTC, alperyazar commented
@all-contributors add @yunusesergun blog

2021-03-13 17:20 UTC, alperyazar commented
@all-contributors add @aniltirli for review