MII sinyallerinde gozlemledigim bir bug hakkinda yazdigim yazi
asynx-dev/www pull request #51
Opened 2020-11-27 12:33 UTC by yunusesergun

2020-11-27 21:11 UTC, alperyazar requested changes
Şekilsel baktım, içeriğe tekrar bakacağım.

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +description: "MII Signal Bug In Xilinx FPGA"
Burayı genelde 1 2 cümle açıklama olarak yazmak daha iyi. Google'da aratınca sonuçlarda bu text çıkıyor.

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +### ETHERNET FRAMES
Başlıkları bu güne kadar hep ilk harf büyük sonra küçük yazdık
```suggestion
### Ethernet frames
```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +### MII SIGNALS
```suggestion
### MII signals
```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +## **ACRHITECTURE**
```suggestion
## Architecture
```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +## **THE BUG**
```suggestion
## The bug
```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +(https://forums.xilinx.com/t5/Ethernet/MII-Signals-Problem-on-ILA/m-p/1126290#M28573)
Bu link iki satıra bölündüğü için çalışmıyor, tek satır olmalı. Lokalde denersen görebilirsin. MD013 açısından linkin uzun olması tek satırda sorun değil.
```suggestion
[Xilinx Forum](https://forums.xilinx.com/t5/Ethernet/MII-Signals-Problem-on-ILA/m-p/1126290#M28573)
```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +Finally, for this bug, I have posted a detailed question on [Xilinx Forum]
```suggestion
Finally, for this bug, I have posted a detailed question on
```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +<!--markdownlint-disable MD034-->
```suggestion

```

2020-11-27 21:11 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +<!--markdownlint-enable MD034-->
```suggestion

```

2020-11-27 21:13 UTC, alperyazar commented
@aniltirli Belki içerik olarak yayınlamadan bir bakmak istersin, 3. göz :) Soru işareti oluşturan yerler varsa yayından önce çözelim.

2020-11-27 21:16 UTC, alperyazar commented
@yunusesergun Mümkün olduğunca PR açmadan önce lokalde siteyi build edip, bir bakmaya çalışırsak daha hızlı bir akış sağlayabiliriz ileriki dönemlerde :)

2020-11-28 16:34 UTC, aniltirli commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +Moreover, I have utilized **Linux Driver** for setupping transmission with
setting up / to set up ?

2020-11-28 16:34 UTC, aniltirli commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +calculations. Because they unite a packet, `TX_EN` should not be disasserted
deasserted

2020-11-28 16:35 UTC, aniltirli commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +there is no solution for this problem.
if the receiver side is strict about the specification

2020-11-28 19:40 UTC, alperyazar approved these changes
Teşekkürler

2020-11-28 19:46 UTC, alperyazar requested changes
#70 den dolayı değişiklik (Ekstra iş için üzgünüm 😞 )

2020-11-28 19:46 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +<!--markdownlint-disable MD013-->
#70 den dolayı bu satırı silebilir miyiz? (Ekstra iş için üzgünüm 😞 )
```suggestion
```

2020-11-28 19:46 UTC, alperyazar commented on docs/blog/20/3-mii-signal-bug-in-xilinx-fpga.md
> +<!--markdownlint-enable MD013-->
#70 den dolayı bu satırı silebilir miyiz? (Ekstra iş için üzgünüm 😞 )
```suggestion
```

2020-11-28 19:47 UTC, yunusesergun commented
Hallettim @alperyazar , sıkıntı değil.

2020-11-28 19:48 UTC, alperyazar approved these changes
Tekrar teşekkürler 👍

2020-11-28 19:49 UTC, merged