Atirlioglu socat md
asynx-dev/www pull request #73
Opened 2020-11-30 07:01 UTC by aniltirli

"Serial data communication over TCP" yazisi eklendi.
...

Ping @alperyazar

2020-11-30 12:36 UTC, yunusesergun commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +description: Serial data communication over TCP with socat.
axlang: "en" ifadesi eklenebilir.

2020-11-30 12:39 UTC, yunusesergun commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +to give money but anyway in most cases socat will do the job. I will not discuss
İsteğe bağlı bazı önemli kelimeleri ** ** veya ` ` arasına alarak emphasize edebilirsin. (mesela `socat` gibi.)

2020-12-01 05:15 UTC, yunusesergun requested changes
Ellerine sağlık.

2020-12-01 11:25 UTC, alperyazar requested changes
Öncelikle teşekkürler :)

`hooks/__pycache__/axmkdocs.cpython-39.pyc` dosyasının gelmemesi gerekiyordu, bunu da çıkartabilir miyiz? Bununla ilgili kendime bug report oluşturdum. #78

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +!!! Info You won't need to open serial port with an application like `screen`
Alt satır, 4 boşluk

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Screenshot1.png){:
Placeholder düzeltelim.

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +style="height:98px;width:222px"}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Placeholder](img-4/Screenshot2.png){:
Placeholder düzeltelim

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +style="height:98px;width:222px"}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Placeholder](img-4/Screenshot2.png){:
HTML tag'ları kullanmayalım. Resim formatı `![]()` dışına çıkmayalım. Resim boyutu büyükse düzeltip koyalım, HTML ile küçültmeyelim. Siteyi lokalde görmeden PR açmayalım :)

![image](https://user-images.githubusercontent.com/1757430/100732491-d5a3c180-33dd-11eb-8cb8-6a0acd1a08f4.png)

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +style="float:left; padding-right:100px"}
```suggestion

```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +[^1f]:
Tek satır olursa boşluksuz daha iyi olur.

```suggestion
[^1f]: https://medium.com/@karthiks1701/virtual-serial-ports-hack-for-communication-between-local-scripts-883fda0f60f4
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +[^2f]:
Tek satır

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +[^3f]:
Tek satır

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +[^4f]:
Tek satır

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +```bash
```suggestion
```console
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Screenshot3.png)
Resim isimlendirmelerini var olan yapıya uygun yapalım. `img-4` klasörü olmasın, `img` altında `4-xxx` şeklinde olsun lütfen.
```suggestion
![Placeholder](img/4-Screenshot3.png)
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +style="height:98px;width:222px"}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Placeholder](img-4/Screenshot2.png){:
Resim isimlendirmelerini var olan yapıya uygun yapalım. `img-4` klasörü olmasın, `img` altında `4-xxx` şeklinde olsun lütfen.

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Diagram.png)
Resim isimlendirmelerini var olan yapıya uygun yapalım. `img-4` klasörü olmasın, `img` altında `4-xxx` şeklinde olsun lütfen.
```suggestion
![Placeholder](img/4-Diagram.png)
```

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Screenshot1.png){:
Resim isimlendirmelerini var olan yapıya uygun yapalım. `img-4` klasörü olmasın, `img` altında `4-xxx` şeklinde olsun lütfen.

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +style="height:98px;width:222px"}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Placeholder](img-4/Screenshot2.png){:
Resim isimlendirmelerini var olan yapıya uygun yapalım. `img-4` klasörü olmasın, `img` altında `4-xxx` şeklinde olsun lütfen.

2020-12-01 11:25 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Diagram.png)
Bu görsel senin çizimin midir? Değilse ref verelim.

2020-12-01 11:25 UTC, alperyazar commented on mkdocs.yml
>    - meta
comitten bu dosyayı çıkartalım. `.yml` bu commitle değişmesin. Bu eklentiyi kullanmaya ihityaç varsa ayrı issue üzerinde konuşalım.

2020-12-01 11:26 UTC, alperyazar commented
@aniltirli Ben içeriği henüz okumadım, onu tekrar okuyacağım.

2020-12-01 16:28 UTC, alperyazar requested changes
Ben bunu sbumit etmiştim sanki ama

2020-12-01 17:59 UTC, aniltirli commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Diagram.png)
Benim çizimim

2020-12-01 19:03 UTC, aniltirli commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Placeholder](img-4/Diagram.png)
Benim çizimim

2020-12-01 19:35 UTC, aniltirli commented
ping @alperyazar

2020-12-02 12:10 UTC, alperyazar commented
> Öncelikle teşekkürler :)
> 
> `hooks/__pycache__/axmkdocs.cpython-39.pyc` dosyasının gelmemesi gerekiyordu, bunu da çıkartabilir miyiz? Bununla ilgili kendime bug report oluşturdum. #78

@aniltirli Bu dosya hala comitte duruyor, bunu çıkarabilir miyiz? `hooks/__pycache__/axmkdocs.cpython-39.pyc`

2020-12-02 12:33 UTC, alperyazar requested changes
`hooks/__pycache__/axmkdocs.cpython-39.pyc` da çıkarabilir miyiz?

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +### 3. Create virtual serial port to forward and listen on machine 1
Machine 1 özel isim gibi kullanıldığından bence
```suggestion
### 3. Create virtual serial port to forward and listen on Machine 1
```

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +### 4. Create virtual serial port to forward on machine 2
Machine 2 özel isim olduğundan
```suggestion
### 4. Create virtual serial port to forward on Machine 2
```

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +![Machine 1 console](img/4-Screenshot1.png)&emsp;&emsp;&emsp;&emsp;![Machine 2 console](img/4-Screenshot2.png)
Buna takardım normalde ama kalsın madem :smile:

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +virtual serial port number can differ for your case.
```suggestion
virtual serial port number can differ in your case.
```

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +!!! Info
Buraya acaba şunu da diyebilir miyiz? Windowstaki COM1 buradaki COM1 mi? 1 eskiği, fazlası gibi bir durum var mı mesela?

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +On machine 1, type:
```suggestion
On Machine 1, type:
```

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +On machine 2, type:
```suggestion
On Machine 2, type:
```

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +$ screen /dev/pts/18 115200
Makine 1 in 6 değil mi?

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +$ screen /dev/pts/6 115200
Makine 2 nin 18 değil mi?

2020-12-02 12:33 UTC, alperyazar commented on docs/blog/20/4-serial-data-communication-over-tcp.md
> +Start TCP connection from machine 2 to machine 1 with the IP and port of machine
```suggestion
Start TCP connection from Machine 2 to Machine 1 with the IP and port of machine
```

2020-12-02 13:32 UTC, alperyazar approved these changes
Uğraştırdık biraz :smiley:

2020-12-02 13:32 UTC, alperyazar commented
@yunusesergun Senin için de uygunsa approve edersen merge edeyim.

2020-12-02 17:33 UTC, yunusesergun approved these changes
Eline sağlık

2020-12-02 19:02 UTC, merged

2021-03-13 16:46 UTC, alperyazar commented
@all-contributors add @aniltirli blog

2021-03-13 17:04 UTC, alperyazar commented
@all-contributors add @yunusesergun review